plugins:
  discourse_ticketing_priority_tags:
    default: "immediate|urgent|high|normal|low"
    choices:
      - immediate
      - urgent
      - high
      - normal
      - low
    client: true
    type: list
    allow_any: true
  discourse_ticketing_status_tags:
    default: "new|triaging|underway|waiting|backburner|resolved"
    choices:
      - new
      - triaging
      - underway
      - waiting
      - backburner
      - resolved
    client: true
    type: list
    allow_any: true
  discourse_ticketing_reason_tags:
    default: "cancel-account|confirm-email|onboarding|username"
    choices:
      - cancel-account
      - confirm-email
      - onboarding
      - username
    client: true
    type: list
    allow_any: true
