plugins:
  tickets_enabled:
    default: false
    client: true
    validator: "TicketsEnabledValidator"
  tickets_icon:
    default: 'tag'
    client: true
  tickets_include_group:
    default: ''
    client: true
  tickets_redirect_assigned:
    default: false
    client: true
